# -*- coding: utf-8 -*-
"""analise_por_estado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCeU1MVWeqzd3ja3jI_Fi-XmPIWQdSd-
"""

import pandas as pd
desmatamento = pd.read_csv('Desmatamento.csv')

estado = desmatamento.groupby('estado', as_index=False)['area'].sum().sort_values(by='area', ascending=False)
print(estado)