# -*- coding: utf-8 -*-
"""visualizacao_top5_estados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shUFUaX73Qfi6jF--WhQw_5zI66D4kOL
"""

import pandas as pd
import plotly.express as px

# ======================
# 1. Carregar os dados
# ======================
desmatamento = pd.read_csv('Desmatamento.csv')

# garantir tipos corretos
desmatamento['ano'] = pd.to_numeric(desmatamento['ano'], errors='coerce')
desmatamento['area'] = pd.to_numeric(desmatamento['area'], errors='coerce')

# remover possíveis valores nulos
desmatamento = desmatamento.dropna(subset=['ano', 'area', 'estado'])

# ======================
# 2. Seleciona Top 5 estados
# ======================
top_estados = (
    desmatamento.groupby('estado')['area']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .index
)

# filtrar apenas esses estados
desmatamento_top = desmatamento[desmatamento['estado'].isin(top_estados)]

# ======================
# 3. Agrupar por ano e estado
# ======================
dados = (
    desmatamento_top.groupby(['ano', 'estado'])['area']
    .sum()
    .reset_index()
)

# ======================
# 4. Criar gráfico interativo
# ======================
fig = px.line(
    dados,
    x='ano',
    y='area',
    color='estado',
    markers=True,
    title="Top 5 Estados com Maior Desmatamento na Amazônia Legal"
)

# ======================
# 5. Melhorias visuais
# ======================
fig.update_layout(
    xaxis_title="Ano",
    yaxis_title="Área desmatada (km²)",
    legend_title="Estados",
    template="plotly_white"
)

# ======================
# 6. Mostrar gráfico
# ======================
fig.show()