# -*- coding: utf-8 -*-
"""analise_temporal_desmatamentoipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shUFUaX73Qfi6jF--WhQw_5zI66D4kOL
"""

import pandas as pd
desmatamento = pd.read_csv('Desmatamento.csv')

ano = desmatamento['ano']
ano = pd.to_numeric(ano)
ano_inicial = ano.min()
ano_final = ano.max()
abrangencia = ano_final - ano_inicial

print(f"O periodo abrangido vai de, {ano_inicial}-{ano_final}: {abrangencia} anos")

ano_desmatamento = desmatamento.groupby('ano', as_index=False)['area'].sum()
ano_desmatamento = ano_desmatamento.rename(columns={
    'area': 'desmatamento(km2)'
})

print("")
print(ano_desmatamento.to_string(index=False))
